// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtxyvulbdhtfkuamowzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0eHl2dWxiZGh0Zmt1YW1vd3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTIyMTAsImV4cCI6MjA3NDM4ODIxMH0.B2WgRPi3RaXYS61lFa289j96Qvc_Ci6ZMkNIVg2CiqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});